# version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - share-network
    restart: always

  server:
    build:
      context: ./server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./server/.env.production
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - share-network
  
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./server/.env${NODE_ENV:+.${NODE_ENV}}
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - share-network

networks:
  share-network:
    driver: bridge
