services:
  db:
    image: mysql:8.0
    env_file:
      - ./server/.env.development
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    restart: always
