services:
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
    ports:
      - '80:80'
    depends_on:
      - server
    networks:
      - share-network
    restart: always

  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - ./server/.env
      - ./server/.env.production
    volumes:
      - uploads:/app/uploads
    networks:
      - share-network

  db:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - ./server/.env.production
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - share-network

networks:
  share-network:
    driver: bridge

volumes:
  mysql_data:
  uploads:
